# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-05-12 11:30
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enqairarchiv',
            name='rating',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='client.Rating'),
        ),
        migrations.AlterField(
            model_name='enqbusarchiv',
            name='rating',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='client.Rating'),
        ),
        migrations.AlterField(
            model_name='enqcararchiv',
            name='rating',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='client.Rating'),
        ),
        migrations.AlterField(
            model_name='enqhotelarchiv',
            name='rating',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='client.Rating'),
        ),
        migrations.AlterField(
            model_name='enqinsrncearchiv',
            name='rating',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='client.Rating'),
        ),
        migrations.AlterField(
            model_name='enqtourarchiv',
            name='rating',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='client.Rating'),
        ),
        migrations.AlterField(
            model_name='enqtrainarchiv',
            name='rating',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='client.Rating'),
        ),
        migrations.AlterField(
            model_name='enqvisaarchiv',
            name='rating',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='client.Rating'),
        ),
    ]
