# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-05-14 11:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0002_auto_20180512_1700'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enqair',
            name='additional_information',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='enqairarchiv',
            name='additional_information',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='enqairarchiv',
            name='additional_information_reply',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='enqbus',
            name='additional_information',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='enqbusarchiv',
            name='additional_information',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='enqbusarchiv',
            name='additional_information_reply',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='enqcar',
            name='additional_information',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='enqcararchiv',
            name='additional_information',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='enqcararchiv',
            name='additional_information_reply',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='enqhotel',
            name='additional_information',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='enqhotelarchiv',
            name='additional_information',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='enqhotelarchiv',
            name='additional_information_reply',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='enqinsrnce',
            name='additional_information',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='enqinsrncearchiv',
            name='additional_information',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='enqinsrncearchiv',
            name='additional_information_reply',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='enqtour',
            name='additional_information',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='enqtourarchiv',
            name='additional_information',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='enqtourarchiv',
            name='additional_information_reply',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='enqtrain',
            name='additional_information',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='enqtrainarchiv',
            name='additional_information',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='enqtrainarchiv',
            name='additional_information_reply',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='enqvisa',
            name='additional_information',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='enqvisaarchiv',
            name='additional_information',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='enqvisaarchiv',
            name='additional_information_reply',
            field=models.TextField(blank=True, null=True),
        ),
    ]
