# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-05-16 13:28
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0003_auto_20180514_1659'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='enqairarchiv',
            name='rating',
        ),
        migrations.RemoveField(
            model_name='enqbusarchiv',
            name='rating',
        ),
        migrations.RemoveField(
            model_name='enqcararchiv',
            name='rating',
        ),
        migrations.RemoveField(
            model_name='enqhotelarchiv',
            name='rating',
        ),
        migrations.RemoveField(
            model_name='enqinsrncearchiv',
            name='rating',
        ),
        migrations.RemoveField(
            model_name='enqtourarchiv',
            name='rating',
        ),
        migrations.RemoveField(
            model_name='enqtrainarchiv',
            name='rating',
        ),
        migrations.RemoveField(
            model_name='enqvisaarchiv',
            name='rating',
        ),
        migrations.DeleteModel(
            name='Rating',
        ),
    ]
