# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-05-16 16:43
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0004_auto_20180516_1858'),
    ]

    operations = [
        migrations.CreateModel(
            name='Rating',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rate', models.CharField(max_length=15)),
                ('stars', models.IntegerField()),
            ],
        ),
        migrations.AddField(
            model_name='enqairarchiv',
            name='rating',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='client.Rating'),
        ),
        migrations.AddField(
            model_name='enqbusarchiv',
            name='rating',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='client.Rating'),
        ),
        migrations.AddField(
            model_name='enqcararchiv',
            name='rating',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='client.Rating'),
        ),
        migrations.AddField(
            model_name='enqhotelarchiv',
            name='rating',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='client.Rating'),
        ),
        migrations.AddField(
            model_name='enqinsrncearchiv',
            name='rating',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='client.Rating'),
        ),
        migrations.AddField(
            model_name='enqtourarchiv',
            name='rating',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='client.Rating'),
        ),
        migrations.AddField(
            model_name='enqtrainarchiv',
            name='rating',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='client.Rating'),
        ),
        migrations.AddField(
            model_name='enqvisaarchiv',
            name='rating',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='client.Rating'),
        ),
    ]
