# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-05-12 10:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agent',
            name='rating',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
