# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-05-12 10:31
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('client', '0001_initial'),
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EnqAirReply',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('flight_names', models.TextField()),
                ('dates_and_timings', models.TextField()),
                ('fares', models.TextField()),
                ('additional_information', models.TextField(blank=True)),
                ('replied', models.DateTimeField(auto_now_add=True)),
                ('agent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='airpending', to='accounts.Agent')),
                ('enq', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='airreply', to='client.EnqAir')),
            ],
        ),
        migrations.CreateModel(
            name='EnqBusReply',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bus_timings', models.TextField()),
                ('fares', models.TextField()),
                ('additional_information', models.TextField(blank=True)),
                ('replied', models.DateTimeField(auto_now_add=True)),
                ('agent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='buspending', to='accounts.Agent')),
                ('enq', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='busreply', to='client.EnqBus')),
            ],
        ),
        migrations.CreateModel(
            name='EnqCarReply',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vehicles_available', models.TextField()),
                ('charges', models.TextField()),
                ('additional_information', models.TextField(blank=True)),
                ('replied', models.DateTimeField(auto_now_add=True)),
                ('agent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='carpending', to='accounts.Agent')),
                ('enq', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='carreply', to='client.EnqCar')),
            ],
        ),
        migrations.CreateModel(
            name='EnqHotelReply',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('names_of_hotels', models.TextField()),
                ('prices_of_hotels', models.TextField()),
                ('location_of_hotels', models.TextField()),
                ('additional_information', models.TextField(blank=True)),
                ('replied', models.DateTimeField(auto_now_add=True)),
                ('agent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hotelpending', to='accounts.Agent')),
                ('enq', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hotelreply', to='client.EnqHotel')),
            ],
        ),
        migrations.CreateModel(
            name='EnqInsrnceReply',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('insurance_coverage', models.TextField()),
                ('charges', models.TextField()),
                ('additional_information', models.TextField(blank=True)),
                ('replied', models.DateTimeField(auto_now_add=True)),
                ('agent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='insrncepending', to='accounts.Agent')),
                ('enq', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='insrncereply', to='client.EnqInsrnce')),
            ],
        ),
        migrations.CreateModel(
            name='EnqTourReply',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('names_of_cities', models.TextField()),
                ('budget', models.CharField(max_length=15)),
                ('additional_information', models.TextField(blank=True)),
                ('replied', models.DateTimeField(auto_now_add=True)),
                ('agent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tourpending', to='accounts.Agent')),
                ('enq', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tourreply', to='client.EnqTour')),
            ],
        ),
        migrations.CreateModel(
            name='EnqTrainReply',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('names_of_trains', models.TextField()),
                ('train_timings', models.TextField()),
                ('days_of_running', models.TextField()),
                ('fares', models.TextField()),
                ('additional_information', models.TextField(blank=True)),
                ('replied', models.DateTimeField(auto_now_add=True)),
                ('agent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trainpending', to='accounts.Agent')),
                ('enq', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trainreply', to='client.EnqTrain')),
            ],
        ),
        migrations.CreateModel(
            name='EnqVisaReply',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('charges', models.CharField(max_length=50)),
                ('additional_information', models.TextField(blank=True)),
                ('replied', models.DateTimeField(auto_now_add=True)),
                ('agent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='visapending', to='accounts.Agent')),
                ('enq', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='visareply', to='client.EnqVisa')),
            ],
        ),
    ]
