# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-05-12 10:31
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Attrac',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=64)),
                ('pic', models.ImageField(upload_to='attractions')),
            ],
        ),
        migrations.CreateModel(
            name='Destinat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, unique=True)),
                ('descrip', models.TextField()),
                ('reach', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='DestType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dtype', models.CharField(max_length=64)),
            ],
        ),
        migrations.AddField(
            model_name='destinat',
            name='dtype',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='places', to='gly.DestType'),
        ),
        migrations.AddField(
            model_name='attrac',
            name='place',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attrct', to='gly.Destinat'),
        ),
    ]
