# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-05-19 21:05
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('gly', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Img',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(upload_to='images')),
                ('place', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='img', to='gly.Destinat')),
            ],
        ),
        migrations.AddField(
            model_name='attrac',
            name='detl',
            field=models.TextField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
