# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-05-20 15:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gly', '0002_auto_20180520_0235'),
    ]

    operations = [
        migrations.CreateModel(
            name='PMessage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=64)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('subject', models.CharField(blank=True, max_length=142)),
                ('message', models.TextField(blank=True)),
            ],
        ),
    ]
